### ISSUE TITLE
Feature request: allow interval jobs to be offset by a random value

### ISSUE THREAD

**Issue by mprpic** [agronholm/apscheduler#168]
When jobs are configured to execute at certain times, they tend to coalesce at one particular time. For example, executing 10 jobs at the top of the hour, another 10 once in at noon and once at midnight, and a third job that executes every minute will cause all of these jobs to run at the same time at noon and midnight, potentially causing a bottleneck in the number of threads.

This could be solved by introducing a new parameter to the interval trigger that would define a value in seconds by which each job would be offset.

Assuming these new imports:
``` python
from operator import add, sub
from random import randrange, choice
```
The constructor could have a new parameter value (`random_offset`) that would be at most equivalent to the configured interval:
``` python
self.random_offset = min(self.interval_length, random_offset)
```
Then, the `get_next_fire_time()` function could check if an offset is defined and modify the next execution time accordingly:
``` python
if self.random_offset:
    offset = timedelta(seconds=randrange(0, self.random_offset))
    op = choice((add, sub))
    next_fire_time = max(datetime.now(self.timezone), op(next_fire_time, offset))
```
I understand all this can be worked around by setting custom start times for each group of jobs so that they don't intersect but having an easy-to-configure parameter would be cool too. The UNIX Anacron scheduler uses a similar mechanic with the [`RANDOM_DELAY` option](http://man7.org/linux/man-pages/man5/anacrontab.5.html).

I did notice during testing of the above code that `get_next_fire_time()` is called both from `_get_run_times()` (in `job.py`) and `_process_jobs` in (in `base.py`), producing different times for each. I'm not sure if it's significant that these functions both receive the same next fire time.

Anyway, is this something you'd consider merging if I were to submit a PR? Thank you!

**Comment by iranzo** [comment]
I was trying to locate something similar... my script uses sqlite and several `cleanup` jobs from different tasks and tables try to kick in at the same time, so sometimes database is locked and program fails.

Something like this would be great, if not, I'll probably switch to cron-style scheduler and set a different start minute

**Comment by agronholm** [comment]
I suggest you subclass the `IntervalTrigger` class and modify the output of `get_next_fire_time()` method.

**Comment by gilbsgilbs** [comment]
Hi,

It would definitely be handy if this was built-in. It's a really common use-case. I can imagine two features out of randomness:

0. Execute the job with a delay of ±x seconds. This allows randomizing execution time. It would prevent all jobs to be trigger at the exact same time and has obvious benefits. It also allows a weak round-robin between nodes when the first node that executes the job is the one that wins.
0. Execute the job with a given probability. You use a random variable to decide whether the job should execute or not. This is especially useful for short `IntervalTrigger` because it's a way to strengthen the round-robin.

It is true that it's possible to subclass existing triggers to achieve this. I've been using this piece of code for a while and it works fine (also have some tests for it):
```python
class FuzzyIntervalTrigger(IntervalTrigger):
    def __init__(self, *args, **kwargs):
        """
        FuzzyTrigger allows to schedule jobs that will execute at fuzzy intervals.
        Jobs will fire every interval ± max_fuzz, with a given probability.

        e.g. seconds = 300, max_fuzz = 30, probability = .5 means that one time out of two, the job will fire at
        interval ± max_fuzz.

        :param max_fuzz: The maximum uncertainty on the next fire. Task will neither trigger before interval - max_fuzz,
        nor after interval + max_fuzz (Default: 0)
        :type max_fuzz: float|int
        :param probability: The probability with which the task should execute. 1 means the task will always execute,
        .5 means the task will execute one time out of two. Too small values will affect performances. 0 will loop
        indefinitely. (Default: 1.)
        :type probability: float|int
        :param args: IntervalTrigger args
        :param kwargs: IntervalTrigger kwargs
        """
        self.__max_fuzz = kwargs.pop('max_fuzz', 0)
        self.__probability = kwargs.pop('probability', 1.)

        super().__init__(*args, **kwargs)

    def get_next_fire_time(self, previous_fire_time, now):
        SAFEGUARD = 10000
        for _ in range(0, SAFEGUARD):
            next_fire_time = super().get_next_fire_time(previous_fire_time, now)
            if next_fire_time is None:
                return None
            next_fire_time += datetime.timedelta(seconds=random.uniform(self.__max_fuzz * -1, self.__max_fuzz))
            if next_fire_time < now:
                next_fire_time = now
            if random.random() < self.__probability:
                return next_fire_time
            now = previous_fire_time or now
            previous_fire_time = next_fire_time
        raise RuntimeError('Infinite loop detected.')
```

**BUT** it would be great if this was more deeply integrated with APScheduler, allowing this type of API:
```python
IntervalTrigger(seconds=5, probability=.5, fuzzyness=5)
CronTrigger(hour=22, fuzzyness=600)
``` 

I'm keen on contributing for this. Just let me know how if the wontfix could be reconsidered and how you would see the API.

**Comment by agronholm** [comment]
How do you figure it's a common use case?

**Comment by gilbsgilbs** [comment]
@agronholm You're right, it's mostly based on a personal perception that might be far from reality, but here are the clues that made me say that:
- It's been asked and implemented on competitors projects: https://github.com/dbader/schedule/issues/89
- As soon as you have multiple nodes, this is something you naturally want to achieve.
- We're at least three that said out loud that APScheduler would benefit from such features. Guess how many people might not have taken time to fill an issue or to comment on a wontfix issue.

I'm not willing to be offending at all and I might be wrong, but a zookeeper or rethinkdb jobstore seems far less common use-cases for instance (at least in the communities I know). Moreover, they could easily be re-implemented or exported into third-party packages, unlike the API I proposed.

**Comment by agronholm** [comment]
> As soon as you have multiple nodes, this is something you naturally want to achieve.

Can you elaborate on this?

> I'm not willing to be offending at all and I might be wrong, but a zookeeper or rethinkdb jobstore seems far less common use-cases for instance (at least in the communities I know). Moreover, they could easily be re-implemented or exported into third-party packages, unlike the API I proposed.

The only reason these back-ends were added is because I well made PRs for both of them.

**Comment by gilbsgilbs** [comment]
> Can you elaborate on this?

Let's say I have 5 nodes and I deployed APScheduler on all of them. I use a memory jobstore and threaded executors. I have idempotent jobs so that I can execute them whenever I want on any of my nodes. I run a job every 10 minutes using an `IntervalTrigger` or a `CronJob`. This job calls an external API + performs some CPU intensive tasks.

- I don't want the loss of one node to compromise the health of the cluster.
- On average, I don't want my nodes to perform the API call at the exact same moment. This would cause a DoS.
- If there's a lock to take for example, I don't want the same node to take it and do all the work everytime. I want the work to be roughly evenly balanced across nodes. (e.g. If one node is unable to do the job for any reason, I want to be informed ASAP + in the case of CPU intensive operations, it's generally a good idea to balance load => CPU credit)
- I want to minimize the number of times I execute the same job on many nodes in the same time interval. It's generally pointless.

The "lean" way to achieve this (I think) is to add a random offset to the job execution (as suggested in this issue) and randomize whether the job executes or not. It's cheap yet good-enough HA and LB without involving a master election, a distributed cron system, a service discovery or such complex and expensive things.

But general case: you know how many sysadmins like to run their cron jobs at fixed non-sharp hours to "respect resources". Having a random offset is just a clean way to address this issue and it's probably what most people here are willing to see.

> The only reason these back-ends were added is because I received well made PRs for both of them.

Given how cool APScheduler is, no doubt it attracts best contributors ;) . Thanks for your time.

**Comment by agronholm** [comment]
Ok, so if I understand correctly, the proposed feature would first calculate the proper next run time and then add a random amount of jitter which would be bound by the given range. I'm willing to pull in such a feature, provided that you include the appropriate test and documentation additions.

Also, with the right kind of wrong settings you may end up calculating a next run time that is the same or earlier than the previous run time. This must never happen, so take that into consideration.

**Comment by agronholm** [comment]
If the jitter is only positive then the problem I described in my previous comment of course doesn't exist.

**Comment by mprpic** [comment]
> Also, with the right kind of wrong settings you may end up calculating a next run time that is the same or earlier than the previous run time. This must never happen, so take that into consideration.

The implementation that I noted in the initial comment ensures this by always computing a time that is a minimum between the interval between two jobs and the configured random delay (jitter). So if you have jobs configured to run every 5 minutes but configure the random delay to be 10 minutes, the maximum time of the offset will still only be 5 minutes so as to not overrun to the next job or interrupt a previously scheduled job (if that makes sense).
