### ISSUE TITLE
"Unable to restore job -- removing it." Really?

### ISSUE THREAD

**Issue by vdedyukhin** [agronholm/apscheduler#341]
What a stupid idea - to remove all jobs without asking permission to do it. I don't get it.
If we start apscheduler 3.4.0 on the database which was used by apscheduler 3.5.0 then everything is instantly lost. Okay, we need version 2 of CronTrigger, but we have version 1. But aren't there a possibility to upgrade? Why do I have to recreate all jobs once again like I have nothing else to do?
What's another library or app with the same logic? Excel 2003 cannot open Excel 2010 files but it doesn't erase them as well! I can't believe somebody really considers this logic normal.

**Comment by agronholm** [comment]
The scheduler is in need of a redesign, but the problem stems from the fact that there is (in the current design) no other way to automatically remove jobs targeted at functions that no longer exist. As for upgrades, those are not a problem. The situation you described, however, is running an older version of APScheduler against a database created by a newer version. This library was originally made for simple recurring in-memory jobs but organically grew to support persistent jobs.

In the future, I recommend that you offer a practical solution instead of whining about the current one.
