### ISSUE TITLE
import error in python 3.6

### ISSUE THREAD

**Issue by guoliangli123** [agronholm/apscheduler#358]
This issue tracker is **ONLY** for reporting bugs.
Issues other than bug reports will be summarily closed.

Any support questions or feature requests should be directed to:

* [StackOverflow](http://stackoverflow.com/questions/tagged/apscheduler)
* [Gitter](https://gitter.im/apscheduler/Lobby)
* [Google groups](http://groups.google.com/group/apscheduler)

## Expected Behavior
when I use apscheduler,I meet import error,my Python version is 3.6

## Current Behavior

Traceback (most recent call last):
  File "D:/python/ctQuant/model/schedule.py", line 8, in <module>
    from apscheduler.schedulers.blocking import BlockingScheduler
  File "C:\Users\guoliangli213070\AppData\Local\Programs\Python\Python36\lib\site-packages\apscheduler\__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
  File "C:\Users\guoliangli213070\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 26, in <module>
    import zipfile
  File "C:\Users\guoliangli213070\AppData\Local\Programs\Python\Python36\lib\zipfile.py", line 84, in <module>
    sizeEndCentDir = struct.calcsize(structEndArchive)
AttributeError: module 'struct' has no attribute 'calcsize'
## Steps to Reproduce

my code is just like 
`
from apscheduler.schedulers.blocking import BlockingScheduler
`

**Comment by Hanaasagi** [comment]
From the trackback, we can know that
`apscheduler` use `pkg_resources` to collect resource in package. And `pkg_resource` is installed with `setuptools`. In https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L26, it `import zipfile`. The real cause of the problem is `struct.calcsize` in zipfile module line 86. But in Python 3.6 doc, `struct` does have a attribute named `calcsize`(https://docs.python.org/3.6/library/struct.html#struct.calcsize)

Maybe your Python environment has something wrong or you modify the `sys.path` to change the import path

**Comment by guoliangli123** [comment]
Think you very mach! I had found the error .
Because I make a module named struct,it have conflict with apscheduler.I renamed the module and every thing goes well.
