### ISSUE TITLE
apscheduler with socket emit not working

### ISSUE THREAD

**Issue by ganeshsingamaneni** [agronholm/apscheduler#454]
iam trying to use schdule intervel jobs and its working fine, when a job is triggered i want to emit the data using socket, but socket emit is not working.

**Comment by agronholm** [comment]
I don't understand how socket functionality is a problem with APScheduler. Please at least follow the bug report template.

**Comment by ganeshsingamaneni** [comment]
sorry for the bug report template, in APScheduler function iam emitting an socket but client side unable to listen to it.

**Comment by agronholm** [comment]
Why are you reporting this as an APScheduler bug? If you want help with your code, use any of the forums listed in the [getting help](https://apscheduler.readthedocs.io/en/stable/userguide.html#getting-help) section of the documentation.
Whatever the case, next time explain the problem in detail. Nobody is going to be able to guess what the problem is based on such a short description.
