### ISSUE TITLE
MemoryJobStore

### ISSUE THREAD

**Issue by qkum** [agronholm/apscheduler#550]
**Describe the bug**

Trying to find out how to use this lib but it is only for veteran programmers it seems.

The tutorial is horrible. 

I'm stuck at finding out how to not use a database on a web application...with "MemoryJobStore"? But there is 0 help to find and the example file seems to be deleted.

Not even a silly youtube video on how to set up and use it. (the one i found the guy spoke horrible English)

This is insane in 2021.

**Expected behavior**
Cover everything in the lib and don't be so greedy on giving some free code examples away + a silly video.

**Additional context**
Sorry for being pissed, but how can I not be pissed when a "highly skilled" programmer can code but not get 1 person out of billions of people in the world to write a little text that covers it all from a to z. With some code examples that I know all of you who use this lib regularly got on your pc ready to upload.

This is unacceptable quality.

Either you do something 100% or 0%.

It is that simple.

- This is a censored complaint, so if you think this is bad, you don't want to see the uncensored version. People like you piss me more off than anything else on planet earth. People like you make the world a worse place. Pull together and add the last 10% you have been too lazy and skip so the documentation becomes acceptable.
If it is more than 1 person who maintains this lib there is even less of an excuse to piss other people off every day and destroying their day.

**Comment by codingadvocate** [comment]
If I were looking for help on an open-source (free) library, I probably would have gone at it a bit differently.

Regarding this comment:
"but not get 1 person out of billions of people in the world to write a little text that covers it all from a to z. With some code examples that I know all of you who use this lib regularly got on your pc ready to upload."

Ok, so you think there's more that can be provided.  Sounds like you're a great candidate to roll your sleeves up and get to work on whatever code samples you think are missing, along with whatever instructional videos you think would help others.  ;)  

Personally, what I found was sufficient for me.  I appreciated the functionality from it - not to mention the free support.

I'm sure some simple searching on GitHub would have turned out plenty of projects that use this library, for potentially more sample code.  Here's one: https://github.com/opencontentplatform/ocp 

Have an awesome day!

**Comment by agronholm** [comment]
Although you are not the first of the few entitled assholes I've come across during the 12 years I've been developing this library, you are the worst. I hope that I can at least get out of you the pain points you were facing.

I develop this library on my own, on my free time in addition to my paid work and multiple other F/OSS projects. You come at me with expectations usually associated with a big team of active developers and one or more sponsors. And it seems you didn't even try to use any of the [support channels](https://apscheduler.readthedocs.io/en/3.x/userguide.html#getting-help) mentioned in the documentation. Not all projects even have any, and many don't even have as much as an API reference. The APScheduler documentation is among the better ones in the Python ecosystem, while admittedly not up to the standards of, say, SQLAlchemy or Django.

> The tutorial is horrible.

Does this mean it does not cover your particular use case, or that it explains the concepts poorly? Any **constructive** criticism is welcome.

> I'm stuck at finding out how to not use a database on a web application...with "MemoryJobStore"? But there is 0 help to find and the example file seems to be deleted.

To **not** use a database, just don't configure one? As the documentation states: `The default job store simply keeps the jobs in memory, but others store them in various kinds of databases.`. Using the memory store in a web app is usually a bad idea because when you add more workers, they will all run the jobs you add at startup. The [FAQ](https://apscheduler.readthedocs.io/en/3.x/faq.html#how-do-i-use-apscheduler-in-a-web-application) contains information about using APScheduler with web apps. It's not a great experience at the moment but APScheduler 4 should change all that.

When I started the development of APScheduler 4, I used the master branch for that work and branched off the "production" version to the 3.x branch. This turned out to be a mistake which I will not repeat. It caused some documentation links to go wonky, and it seems that I forgot to fix the documentation link on PyPI which linked to the development version and not the default one which is 3.x. For this I do apologize. But, you could've at least asked on any of the support channels before blasting at me like this. And for the record, I have fixed the links on the PyPI page now.

> Not even a silly youtube video on how to set up and use it. (the one i found the guy spoke horrible English)

I'm not doing any youtube videos. I would argue that the vast majority of Python libraries don't have any.

> This is a censored complaint, so if you think this is bad, you don't want to see the uncensored version. People like you piss me more off than anything else on planet earth. People like you make the world a worse place. Pull together and add the last 10% you have been too lazy and skip so the documentation becomes acceptable.
If it is more than 1 person who maintains this lib there is even less of an excuse to piss other people off every day and destroying their day.

Should I tell you where to shove your entitled bullshit complaints? If you can manage make this exchange a little bit more civil, I would be happy to reciprocate.
