### ISSUE TITLE
Interval start date ignored

### ISSUE THREAD

**Issue by agronholm** [agronholm/apscheduler#97]
Originally reported by: **Alastair McClelland (Bitbucket: [almcc](http://bitbucket.org/almcc), GitHub: [almcc](http://github.com/almcc))**

---

When adding a job with an interval and a startdate of now, the job is not running until the start_date + interval rather than on the start_date. 

```
#!python

scheduler.add_job(my_job, 
                  'interval', 
                  seconds=300,
                  start_date=datetime.now(),
                  max_instances=1,
                  coalesce=True)
```

I believe the issue is in the 'get_next_fire_time' function in the 'IntervalTrigger' function. 

https://bitbucket.org/agronholm/apscheduler/src/f312c39b161011b6c6372960b6985434854fab84/apscheduler/triggers/interval.py?at=master

```
#!python

def get_next_fire_time(self, previous_fire_time, now):
        if previous_fire_time:
            next_fire_time = previous_fire_time + self.interval
        elif self.start_date > now: #  Should this not be elif self.start_date < now:
            next_fire_time = self.start_date
        else:
            timediff_seconds = timedelta_seconds(now - self.start_date)
            next_interval_num = int(ceil(timediff_seconds / self.interval_length))
            next_fire_time = self.start_date + self.interval * next_interval_num

        if not self.end_date or next_fire_time <= self.end_date:
            return self.timezone.normalize(next_fire_time)
```

I flicked the '>' to a '<' (see inline comment) and everything seemed to work as expected for me after that. 

I have only just started using APScheduler so I may have got something wrong, it is of course an awesome tool. 

Cheers

Al

---
- Bitbucket: https://bitbucket.org/agronholm/apscheduler/issue/97

**Comment by luyu12** [comment]
Hi Alex,

Just kinda want to confirm if this issue is still ongoing? I think I'm having the similar issue as this. In my scenario, I'm expecting that the job should be triggered right after the scheduler starts for the first time run. 
`class worker():
    def __init__(self,...):
        ...
    self._add_job(id=self.name,func=self._run,max_instances=1,trigger=IntervalTrigger(**self.trigger_args))
    self.scheduler.start()
`
Like you mentioned in the comments, I've verified that next_run_time=datetime.now() could work locally. But what I don't understand is that, first set now()(ie, at time x) to the job, and then start the scheduler(ie, at time x + 1) which would miss out the past 'now()', so could lead to the job firstly run at next interval instead of now.

**Comment by agronholm** [comment]
This has been rectified in master (upcoming v4.0). The workaround is to specify a next run time as the current time (`next_run_time=datetime.now()`).
